-- MySQL Script generated by MySQL Workbench
-- Fri May  1 07:40:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `balance` DOUBLE NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sellers` (
  `user_id` VARCHAR(36) NOT NULL,
  `rating` DOUBLE NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_sellers_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_sellers_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `starting_price` DOUBLE NOT NULL,
  `current_highest_price` DOUBLE NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `seller_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_items_sellers1_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_sellers1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `mydb`.`sellers` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bidders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bidders` (
  `user_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_bidders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admins` (
  `user_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_admins_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bids` (
  `id` VARCHAR(36) NOT NULL,
  `bid_amount` DOUBLE NOT NULL,
  `bid_time` DATETIME NOT NULL,
  `bidder_id` VARCHAR(36) NOT NULL,
  `item_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bids_bidders1_idx` (`bidder_id` ASC) VISIBLE,
  INDEX `fk_bids_items1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_bids_bidders1`
    FOREIGN KEY (`bidder_id`)
    REFERENCES `mydb`.`bidders` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bids_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
